/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.asteroid.duck.corp.bs;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import javax.ws.rs.core.MediaType;

import static io.restassured.RestAssured.given;


@QuarkusTest
public class AppTest {

    @Test
    void appHasAGreeting() throws Exception {
        given()
                .when()
                    .accept(MediaType.TEXT_PLAIN)
                    .get("/rest/bs")
                .then()
                    .statusCode(200).log().body();
    }
}
