/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.asteroid.duck.corp.bs;

import org.asteroid.duck.corp.bs.input.StreamWordSource;
import org.asteroid.duck.corp.bs.input.WordSource;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.io.InputStream;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

@SpringBootApplication
public class App {
    @Bean
    public static Map<WordType, WordSource> createWordSources() {
        return WordType.inOrder()
                .collect(Collectors.toMap(
                        Function.identity(),
                        wordType -> createWordSource(wordType)));
    }

    private static WordSource createWordSource(WordType type) {
        final String resourceName = "/"+type.name().toLowerCase()+"s.txt";
        InputStream stream = App.class.getResourceAsStream(resourceName);
        if (stream == null) throw new RuntimeException("No such resource "+resourceName);
        return StreamWordSource.wrapInputStream(stream);
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
