/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.asteroid.duck.corp.bs;

import org.asteroid.duck.corp.bs.input.StreamWordSource;
import org.asteroid.duck.corp.bs.input.WordSource;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import java.io.InputStream;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

@ApplicationScoped
public class App {
    @Produces
    public static Map<WordType, WordSource> createWordSources() {
        return WordType.inOrder()
                .collect(Collectors.toMap(
                        Function.identity(),
                        wordType -> createWordSource(wordType)));
    }

    private static WordSource createWordSource(WordType type) {
        final String resourceName = "/"+type.name().toLowerCase()+"s.txt";
        InputStream stream = App.class.getResourceAsStream(resourceName);
        if (stream == null) throw new RuntimeException("No such resource "+resourceName);
        return StreamWordSource.wrapInputStream(stream);
    }
}
